-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
--   at:        2022-01-08 01:25:56 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE USER tema_bd 
    IDENTIFIED BY  
    DEFAULT TABLESPACE USERS 
    QUOTA UNLIMITED ON USERS 
    ACCOUNT UNLOCK 
;

GRANT CREATE VIEW,
    CREATE TRIGGER,
    CREATE SYNONYM,
    CREATE SEQUENCE,
    CREATE INDEXTYPE,
    CREATE SESSION,
    CREATE PROCEDURE,
    CREATE OPERATOR,
    CREATE CLUSTER,
    CREATE JOB,
    CREATE MATERIALIZED VIEW,
    CREATE ANY CONTEXT,
    CREATE TYPE,
    CREATE TABLE, CREATE DIMENSION TO TEMA_BD 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE book (
    book_id          NUMBER NOT NULL,
    title            VARCHAR2(50 CHAR),
    book_author      VARCHAR2(50 CHAR),
    price            NUMBER,
    isbn13           VARCHAR2(50 CHAR),
    num_pages        NUMBER,
    publication_date DATE NOT NULL,
    publisher_id     NUMBER NOT NULL,
    quantity         NUMBER
)
LOGGING;

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( book_id );

CREATE TABLE customer (
    customer_id      NUMBER NOT NULL,
    first_name       VARCHAR2(50 CHAR),
    last_name        VARCHAR2(50 CHAR),
    email            VARCHAR2(100 CHAR),
    adress_customer  VARCHAR2(200 CHAR),
    number_of_orders NUMBER
)
LOGGING;

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE order_book (
    order_id    NUMBER NOT NULL,
    customer_id NUMBER NOT NULL
)
LOGGING;

ALTER TABLE order_book ADD CONSTRAINT order_book_pk PRIMARY KEY ( order_id );

CREATE TABLE order_to_book (
    order_id NUMBER NOT NULL,
    book_id  NUMBER NOT NULL
)
LOGGING;

CREATE TABLE publisher (
    publisher_id   NUMBER NOT NULL,
    publisher_name VARCHAR2(50 CHAR)
)
LOGGING;

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( publisher_id );

ALTER TABLE order_to_book
    ADD CONSTRAINT book_id_fk FOREIGN KEY ( book_id )
        REFERENCES book ( book_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE book
    ADD CONSTRAINT book_publisher_fk FOREIGN KEY ( publisher_id )
        REFERENCES publisher ( publisher_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE order_book
    ADD CONSTRAINT customer_id_fk FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE order_to_book
    ADD CONSTRAINT order_id_fk FOREIGN KEY ( order_id )
        REFERENCES order_book ( order_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

CREATE SEQUENCE book_book_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER book_book_id_trg BEFORE
    INSERT ON book
    FOR EACH ROW
    WHEN ( new.book_id IS NULL )
BEGIN
    :new.book_id := book_book_id_seq.nextval;
END;
/

CREATE SEQUENCE customer_customer_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER customer_customer_id_trg BEFORE
    INSERT ON customer
    FOR EACH ROW
    WHEN ( new.customer_id IS NULL )
BEGIN
    :new.customer_id := customer_customer_id_seq.nextval;
END;
/

CREATE SEQUENCE order_book_order_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER order_book_order_id_trg BEFORE
    INSERT ON order_book
    FOR EACH ROW
    WHEN ( new.order_id IS NULL )
BEGIN
    :new.order_id := order_book_order_id_seq.nextval;
END;
/

CREATE SEQUENCE publisher_publisher_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER publisher_publisher_id_trg BEFORE
    INSERT ON publisher
    FOR EACH ROW
    WHEN ( new.publisher_id IS NULL )
BEGIN
    :new.publisher_id := publisher_publisher_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
commit;