DROP TABLE TEMA_BD.ORDER_TO_BOOK;
DROP TABLE TEMA_BD.BOOK;
DROP TABLE TEMA_BD.PUBLISHER;
DROP TABLE TEMA_BD.CUSTOMER;
DROP TABLE TEMA_BD.ORDER_BOOK;

DROP TRIGGER TEMA_BD.BOOK_BOOK_ID_TRG;
DROP TRIGGER TEMA_BD.ORDER_BOOK_ORDER_ID_TRG;
DROP TRIGGER TEMA_BD.CUSTOMER_CUSTOMER_ID_TRG;
DROP TRIGGER TEMA_BD.PUBLISHER_PUBLISHER_ID_TRG;

DROP SEQUENCE TEMA_BD.BOOK_BOOK_ID_SEQ;
DROP SEQUENCE TEMA_BD.ORDER_BOOK_ORDER_ID_SEQ;
DROP SEQUENCE TEMA_BD.CUSTOMER_CUSTOMER_ID_SEQ;
DROP SEQUENCE TEMA_BD.PUBLISHER_PUBLISHER_ID_SEQ;